---
title: "Week4"
author: "Dmitriy Tsimokha"
date: "12/20/2020"
output: html_document
lang: russian
---

```{r}
library(HSAUR); library(dplyr); library(psych); library(glmnet)
library(ggplot2); library(car)
```

```{r}
h <- cars
qplot(data = h, speed, dist)
```

```{r}
model <- lm(data = h, dist ~ speed)
summary(model)
```

```{r}
h <- mutate(h, speed2 = speed^2, speed3 = speed^3)
model_mk <- lm(data = h, dist ~ speed + speed2 + speed3)
summary(model_mk)
```

**BUT** - p-value of regression shows significance: there is relationships, but with what exactly?

```{r}
vif(model_mk)
```

*A lot of multicollinearity* - VIF > 10

```{r}
x0 <- model.matrix(data = h, dist ~ 0 + speed + speed2 + speed3)
head(x0)

cor(x0)
```

```{r}
nd <- data.frame(speed = 10, speed2 = 100, speed3 = 1000)

predict(model, newdata = nd, interval = "prediction")
predict(model_mk, newdata = nd, interval = "prediction")

confint(model)
confint(model_mk)
```

*Multicollinearity brings much wider bigger confidence intervals (often have 0 inside)*



```{r}
y <- h$dist
x0 <- model.matrix(data = h, dist ~ 0 + speed + speed2 + speed3)
lambdas <- seq(50, 0.1, length = 30)  # From larger to smaller
```

# LASSO regression
```{r}
m_lasso <- glmnet(x0, y, alpha = 1, lambda = lambdas)  # 

plot(m_lasso, xvar = "lambda", label = TRUE)
plot(m_lasso, xvar = "dev", label = TRUE)
plot(m_lasso, xvar = "norm", label = TRUE)  # Sum of abs of B^hat

coef(m_lasso, s = c(0.1, 1))
```

# Ridge regression
```{r}
m_ridge <- glmnet(x0, y, alpha = 0, lambda = lambdas)  # 

plot(m_ridge, xvar = "lambda", label = TRUE)
plot(m_ridge, xvar = "dev", label = TRUE)
plot(m_ridge, xvar = "norm", label = TRUE)  # Sum of abs of B^hat

coef(m_ridge, s = c(0.1, 1))
```

## Cross-validation (on LASSO regression)
```{r}
cv <- cv.glmnet(x0, y, alpha = 1)
plot(cv)  # left - min RSS; right - optimal RSS

cv$lambda.min  # min RSS
cv$lambda.1se  # min betas (closer to 0)

coef(cv, s ="lambda.min")
coef(cv, s ="lambda.1se")
```

# PCA: Principal Component Analysis
```{r}
h <- heptathlon
glimpse(h)
h <- select(h, -score)  # Delete results
describe(h)
cor(h)
# Standardization
h.pca <- prcomp(h, scale = TRUE)
pca1 <- h.pca$x[,1]
v1 <- h.pca$rotation[,1]
v1  # Weights of old variables in new pca1 variable
head(pca1)

summary(h.pca)
cor(heptathlon$score, pca1)  # Exactly the result

plot(h.pca)
biplot(h.pca, xlim = c(-1, 1))
```

# Test
```{r}
df <- airquality
# 15
qplot(df$Ozone, df$Wind)
# 16
model <- lm(data = df, Ozone ~ Solar.R + Wind + Temp)
vif(model)
# 17
df_na <- na.omit(df)
y <- df_na$Ozone
x0 <- model.matrix(data = df_na, Ozone ~ 0 + Solar.R + Wind + Temp)
lambdas <- seq(50, 0.1, length = 30)
m_lasso <- glmnet(x0, y, alpha = 1, lambda = lambdas)
coef(m_lasso, s = 1)
# 18
m_ridge <- glmnet(x0, y, alpha = 0, lambda = lambdas)
coef(m_ridge, s = 2)
# 19
plot(m_lasso, xvar = "norm")
# 20
h.pca <- prcomp(x0, scale = TRUE)
qplot(h.pca$x[,1], h.pca$x[,3])
```









































